discordToken: ${DISCORD_TOKEN}
segmindApiToken: ${SEGMIND_TOKEN}

datasource.driver-class-name: org.postgresql.Driver
datasource.url: ${DB_URL}
datasource.username: ${DB_USERNAME}
datasource.password: ${DB_PASS}
datasource.dialect: org.hibernate.dialect.PostgreSQLDialect

liquibase.change-log: db/changelog/db.changelog-master.yaml
