discordToken: ${DISCORD_TOKEN}
segmindApiToken: ${SEGMIND_TOKEN}

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASS}
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  liquibase:
    change-log: db/changelog/db.changelog-master.yaml
    enabled: true
